#include<iostream>
using namespace std;

int partition(int arr[],int low,int high){
int pivot=arr[low];
int i=low+1;
int j=high;

while(i<=j){
while(i<=high && arr[i]<=pivot)
i++;

while(arr[j]>pivot)
j--;

if(i<j)
swap(arr[i],arr[j]);
}

swap(arr[low],arr[j]);
return j;
}

void quickSort(int arr[],int low,int high){
if(low<high){
int loc=partition(arr,low,high);
quickSort(arr,low,loc-1);
quickSort(arr,loc+1,high);
}
}

int main(){
int n;
cout<<"Enter size: ";
cin>>n;

int arr[n];

cout<<"Enter elements: ";
for(int i=0;i<n;i++)
cin>>arr[i];

quickSort(arr,0,n-1);

cout<<"Sorted Array: ";
for(int i=0;i<n;i++)
cout<<arr[i]<<" ";

return 0;
}